blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [ 
    path('', views.blog, name='article-list'),
    path('<int:pk>/',views.blog_detail, name='article-detail'),
]

blogsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('blog/', include('blog.urls')),
    path('user/', include('user.urls')),
]

info/urls.py
from django.urls import path
from . import views
app_name = 'info'
urlpatterns = [
    path('', views.home,name ='home'),
    path('contact/', views.contact, name='contact')
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField()
    
    def __str__(self):
        return self.user.username

class Tag(models.Model):
    title = models.CharField(max_length=10)
    
    def __str__(self):
        return self.title

class Article(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = models.TextField(null=True, blank=True)
    content = models.TextField()
    show = models.BooleanField(default=True)
    tags = models.ManyToManyField(Tag)
    view_count = models.IntegerField()
    main_image = models.ImageField(null=True, blank=True)
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True)
    created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    

info/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=50)
    message = models.TextField()
    created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return self.name

user/models.py
from django.db import models

# Create your models here.

info/forms.py
from django import forms
from .models import Contact


# class ContactForm(forms.ModelForm):
#     class Meta:
#         model = Contact
#         fields = '__all__'
        

class ContactForm(forms.Form):
    name = forms.CharField(max_length=50, label='Ad Soyad')
    email = forms.EmailField()
    phone = forms.CharField(max_length=50)
    message = forms.CharField(widget=forms.Textarea)
    
    

user/forms.py
from django import forms
from django.contrib.auth.models import User
import re

username_compiler = re.compile(r'^\w{5,}$')


class RegisterForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_again = forms.CharField(widget=forms.PasswordInput)
    
    def save(self):
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        username = self.cleaned_data.get('username')
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = User.objects.create_user(
            username=username, 
            first_name=first_name, 
            last_name=last_name, 
            email=email, 
            password=password
        )
        return user
        

    def clean_username(self):
        username = self.cleaned_data.get('username')
        
        if not username_compiler.match(username):
            raise forms.ValidationError('Username yazilisi duzgun deyil')
        elif User.objects.filter(username=username).exists():
            raise forms.ValidationError('Bu istifadeci adi artiq islenilib')

        return username
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Bu email artiq islenilib')
        
        return email
    
    def clean(self):
        super().clean()
        password = self.cleaned_data.get('password')
        password_again = self.cleaned_data.get('password_again')

        if password and password_again and password != password_again:
            raise forms.ValidationError('Sifreler eyni deyil!')
        

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

        

blog/views.py
from django.shortcuts import render
from .models import Article, Author, Tag

# Create your views here.

def blog(request):
    articles = Article.objects.all()
    authors = Author.objects.all()
    tags = Tag.objects.all()
    author_username = request.GET.get('author')
    tag_title = request.GET.get('tag')
    if author_username:
        articles = articles.filter(author__user__username=author_username)
    if tag_title:
        articles = articles.filter(tags__title=tag_title)
    return render(request,'blog.html', context={
        'articles': articles, 
        'authors': authors,
        'tags': tags
    })

def blog_detail(request, pk):
    article = Article.objects.get(pk=pk)
    return render(request,'blog-detail.html', context={'article': article})

info/views.py
from django.shortcuts import render
from .models import Contact
from .forms import ContactForm

# Create your views here.
def home(request):
    return render(request, 'home.html')

def contact(request):
    if request.method == 'POST':
        form = ContactForm(data=request.POST)
        if form.is_valid():
            # form.save()
            Contact.objects.create(**form.cleaned_data)
        return render(request, 'contact.html', context={'form': form})
    else:
        form = ContactForm()
        return render(request, 'contact.html', context={'form': form})

        

user/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User

# Create your views here.

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = User.objects.filter(username=username).first()
            if user and user.check_password(password):
                login(request, user)
                return redirect('info:home')
            return render(request, 'login.html', context={'form': form, 'invalid_credentials': True})
        return render(request, 'login.html', context={'form': form})
    else:
        form = LoginForm()
        return render(request, 'login.html', context={'form': form})

def register_view(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('info:home')
        return render(request, 'register.html', context={'form': form})
    else:
        form = RegisterForm()
        return render(request, 'register.html', context={'form': form})

def logout_view(request):
    logout(request)
    return redirect('user:login')

blog/templates/blog-detail.html
{% extends 'layout.html' %}
{% load static %}  

{% block main %}
<!-- Page Header-->
<header class="masthead" style="background-image: url('{% static 'assets/img/post-bg.jpg' %}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="post-heading">
                    <h1>{{article.title}}</h1>
                    <h2 class="subheading">{{article.description}}</h2>
                    <span class="meta">
                        Posted by
                        <a href="#!">Start Bootstrap</a>
                        on {{article.created}}
                    </span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Post Content-->
<article class="mb-4">
    <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                {{article.content}}
            </div>
        </div>
    </div>
</article>{% endblock main %}
        
       

blog/templates/blog.html
{% extends 'layout.html' %}
{% load static %}   

{% block main %}
    {% static 'assets/img/about-bg.jpg' as blog_image %}
    {% include 'includes/banner.html' with banner_title='BLOG' banner_description='This is what I do.' banner_image=blog_image %}
      <!-- Main Content-->
      <div class="container px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5">
            <div class="col-md-12 col-lg-4 col-xl-3">
                <div class="h3">Authors</div>
                <ul class="p-0">
                    {% for author in authors %}
                        <li><a href="?author={{author.user.username}}">{{author.user.get_full_name}}</a></li>
                    {% endfor %}
                </ul>
                <hr>
                <div class="h3">Tags</div>
                <ul class="p-0">
                    {% for tag in tags %}
                        <li><a href="?tag={{tag.title}}">{{tag.title}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-12 col-lg-8 col-xl-9">
                {% for article in articles %}
                    <div class="post-preview">
                        <a href="{% url 'blog:article-detail' pk=article.id %}">
                            <h2 class="post-title">{{article.title}}</h2>
                            <h3 class="post-subtitle">{{article.description}}</h3>
                        </a>
                        <p class="post-meta mb-1">
                            Posted by
                            <a href="?author={{article.author.user.username}}">{{article.author.user.get_full_name}}</a>
                            on {{article.created}}
                        </p>
                        <div>
                            {% for tag in article.tags.all %}
                                <a href="?tag={{tag.title}}" class="badge bg-secondary rounded">{{tag.title}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Divider-->
                    <hr class="my-4" />
                {% endfor %}
                <!-- Post preview-->
                
                <!-- Pager-->
                <div class="d-flex justify-content-end mb-4"><a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a></div>
            </div>
        </div>
    </div>


{% endblock main %}
  

blog/templates/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for user in user_list %}
        {% if forloop.first %}
            <div style="color: gold;">
                <h1>{{forloop.counter}}. {{user.name}}</h1>
                <h3>{{user.age}}</h3>
                <h3>{{user.job}}</h3>
            </div>
        {% elif forloop.last %}
            <div style="color: red;">
                <h1>{{forloop.counter}}. {{user.name}}</h1>
                <h3>{{user.age}}</h3>
                <h3>{{user.job}}</h3>
            </div>
        {% else %}
            <div>
                <h1>{{forloop.counter}}. {{user.name}}</h1>
                <h3>{{user.age}}</h3>
                <h3>{{user.job}}</h3>
            </div>
        {% endif %}
    {% endfor %}

    {% comment %} <p>{{text|truncatechars:50}}</p> {% endcomment %}
    <p>{{language|upper}}</p>
    <p>{{language|lower}}</p>
</body>
</html>

info/templates/contact.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}
    <!-- Page Header-->
    {% static 'assets/img/contact-bg.jpg' as contact_image %}
    {% include 'includes/banner.html' with banner_title='Contact Me' banner_description='Have questions? I have answers.' banner_image=contact_image %}
    <!-- Main Content-->
    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
                    <div class="my-5">
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- * * SB Forms Contact Form * *-->
                        <!-- * * * * * * * * * * * * * * *-->
                        <!-- This form is pre-integrated with SB Forms.-->
                        <!-- To make this form functional, sign up at-->
                        <!-- https://startbootstrap.com/solution/contact-forms-->
                        <!-- to get an API token!-->

                        <form action="{% url 'info:contact' %}" method="POST">
                            {% csrf_token %}
                            {{form.as_div}}
                            <button type="submit">Gonder</button>
                        </form>

                        {% comment %} <form id="contactForm" data-sb-form-api-token="API_TOKEN">
                            <div class="form-floating">
                                <input class="form-control" id="name" type="text" placeholder="Enter your name..." data-sb-validations="required" />
                                <label for="name">Name</label>
                                <div class="invalid-feedback" data-sb-feedback="name:required">A name is required.</div>
                            </div>
                            <div class="form-floating">
                                <input class="form-control" id="email" type="email" placeholder="Enter your email..." data-sb-validations="required,email" />
                                <label for="email">Email address</label>
                                <div class="invalid-feedback" data-sb-feedback="email:required">An email is required.</div>
                                <div class="invalid-feedback" data-sb-feedback="email:email">Email is not valid.</div>
                            </div>
                            <div class="form-floating">
                                <input class="form-control" id="phone" type="tel" placeholder="Enter your phone number..." data-sb-validations="required" />
                                <label for="phone">Phone Number</label>
                                <div class="invalid-feedback" data-sb-feedback="phone:required">A phone number is required.</div>
                            </div>
                            <div class="form-floating">
                                <textarea class="form-control" id="message" placeholder="Enter your message here..." style="height: 12rem" data-sb-validations="required"></textarea>
                                <label for="message">Message</label>
                                <div class="invalid-feedback" data-sb-feedback="message:required">A message is required.</div>
                            </div>
                            <br />
                            <!-- Submit success message-->
                            <!---->
                            <!-- This is what your users will see when the form-->
                            <!-- has successfully submitted-->
                            <div class="d-none" id="submitSuccessMessage">
                                <div class="text-center mb-3">
                                    <div class="fw-bolder">Form submission successful!</div>
                                    To activate this form, sign up at
                                    <br />
                                    <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                </div>
                            </div>
                            <!-- Submit error message-->
                            <!---->
                            <!-- This is what your users will see when there is-->
                            <!-- an error submitting the form-->
                            <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            <!-- Submit Button-->
                            <button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
                        </form> {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock main %}

info/templates/home.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}
     <!-- Page Header-->
     {% comment %} 
     <header class="masthead" style="background-image: url('{{home_image}}')">      
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="page-heading">
                        <h1>Home</h1>
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header> {% endcomment %}
    {% static 'assets/img/about-bg.jpg' as home_image %}
    {% include 'includes/banner.html' with banner_title='Home' banner_description='his is what I do.' banner_image=home_image %}
    <!-- Main Content-->
    <main class="mb-4">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>
                </div>
            </div>
        </div>
    </main>
{% endblock main %}

templates/includes/banner.html
{% load static %}

<header class="masthead" style="background-image: url('{{banner_image}}')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="page-heading">
                    <h1>{{banner_title}}</h1>
                    <span class="subheading">{{banner_description}}</span>
                </div>
            </div>
        </div>
    </div>
</header>

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Clean Blog - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'info:home'%}">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'info:home'%}">Home</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'blog:article-list' %}">Blog</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'info:contact' %}">Contact</a></li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'user:logout' %}">Logout</a></li>
                        {% else %}
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'user:login' %}">Login</a></li>
                            <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'user:register' %}">Register</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block main %}{% endblock main %}
        <!-- Footer-->
        <footer class="border-top">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                        <ul class="list-inline text-center">
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!">
                                    <span class="fa-stack fa-lg">
                                        <i class="fas fa-circle fa-stack-2x"></i>
                                        <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2022</div>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

user/templates/login.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}
    {% static 'assets/img/about-bg.jpg' as home_image %}
    {% include 'includes/banner.html' with banner_title='Login' banner_description='Hurry up to chekout new contents' banner_image=home_image %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-6 bg-light border border-dark p-3">
                <div class="row">
                    <div class=""><div class="h2 text-center">Login</div></div>
                    {% if invalid_credentials %}
                        <div class="h4 text-danger">Username or password is incorrect</div>
                    {% endif %}
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_div}}
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}

user/templates/register.html
{% extends 'layout.html' %}
{% load static %}

{% block main %}
    {% static 'assets/img/about-bg.jpg' as home_image %}
    {% include 'includes/banner.html' with banner_title='Register' banner_description='Join to us.' banner_image=home_image %}
    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-6 bg-light border border-dark p-3">
                <div class="row">
                    <div class=""><div class="h2 text-center">Register</div></div>
                    <form method="POST">
                        {% csrf_token %}
                        {{form.as_div}}
                        <input type="submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock main %}